version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "10:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: eslint
    versions:
    - 7.22.0
  - dependency-name: eslint-plugin-jest
    versions:
    - 24.2.0
  - dependency-name: stylelint
    versions:
    - 13.10.0
